### PR TITLE
Close the socket when authentication verification fails

### LINKED ISSUE #260: Close the socket when authentication expires
When a websocket requires authentication, and the server uses some sort of token based authentication, the credentials usually have a limited lifetime. The `nes` clients are free to `overrideReconnectionAuth()` and provide new credentials for the case when the websocket drops, however if the websocket does not drop - it still assumes the old credentials on the server side. This means that the websocket is open to send/receive information even though the client may no longer have valid credentials, which could be a security issue in some contexts.

## Proposal

* Registration options should accept an `auth.expiresAt` callback.
* ~~When the authentication endpoint accepts valid credentials, it should `const expiresAt = await auth.expiresAt(request.auth);`.~~ After the client authenticates, the server should `const expiresAt = await auth.expiresAt(credentials, artifacts);`.
* The websocket should be closed on the server side at `expiresAt` time. `undefined` means never expire.
* When the client calls ~~`overrideReconnectionAuth()`~~ `reauthenticate()`, it should also make a request to the authentication endpoint, so that the server can update the `expiresAt` time and extend the websocket lifetime.

### PR DESCRIPTION
**Pull request by dominykas**
Closes #260.

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -65,7 +66,8 @@ internals.schema = Joi.object({
         ]),
         index: Joi.boolean(),
         timeout: Joi.number().integer().min(1).allow(false),
-        maxConnectionsPerUser: Joi.number().integer().min(1).allow(false).when('index', { is: true, otherwise: Joi.valid(false) })
+        maxConnectionsPerUser: Joi.number().integer().min(1).allow(false).when('index', { is: true, otherwise: Joi.valid(false) }),
+        verify: Joi.number().integer()
```
Comment (dominykas) [inline lib/index.js]: @hueniverse you mentioned you'd like to see a `min` here? Aside from Joi trickery to achieve that - is there really a need for that?

File: lib/socket.js [hunk 2]
```diff
@@ -551,11 +588,33 @@ internals.Socket.prototype._setCredentials = function (credentials, artifacts) {
...
 
 
+internals.Socket.prototype._verifyAuth = function () {
+
+    if (!this.auth.isAuthenticated) {
+        // no credentials available - no need to verify them
+        return true;
+    }
+
+    if (Date.now() - this.auth._verified < this._listener._settings.auth.verify) {
```
Comment (dominykas) [inline lib/socket.js]: I'm not adding a way to disable this completely - should I? By e.g. setting `verify: false`?

File: lib/socket.js [hunk 3]
```diff
@@ -263,6 +264,11 @@ internals.Socket.prototype._lifecycle = function (request) {
         throw Boom.badRequest('Message missing id');
     }
 
+    if (!this._verifyAuth()) {
```
Comment (dominykas) [inline lib/socket.js]: I only added this for received messages, because of the heartbeat. If the server receives no heartbeat - it will disconnect anyways. There is a chance of someone configuring a very long heartbeat timeout and keeping on pushing messages, but is that an issue?

File: lib/index.js (hunk 1 above)
Comment (hueniverse) [reply lib/index.js]: The point of making sure this is not less than the heartbeat rate is to set expectations. If you want to verify the connection faster than the heartbeat check, it will still only happen as fast as messages are passing through or the heartbeat check.

Also, `verify` is not very descriptive. I prefer `minAuthVerifyIntervalMsec`.

File: lib/socket.js (hunk 2 above)
Comment (hueniverse) [reply lib/socket.js]: Sounds reasonable. `false` works for me.
